### ISSUE TITLE
Не работают филиалы

### ISSUE THREAD

**Issue by kirilovsasha** [leon-mbs/zstore_ru#1]
Здравствуйте! Филиалы добавляются в настройках, однако на главной странице вверху в форме "Филиал" одно значение "Все доступные". Страницу обновлял и т.д. - не помогает. Может подскажите, что делать. Спасибо. 
![image](https://github.com/leon-mbs/zstore_ru/assets/120123810/fe27d455-0106-4bf1-9edb-7e4671e2e289)

**Comment by kirilovsasha** [comment]
Помог перелогин)

**Comment by leon-mbs** [comment]
там написано - после  изменения  настроек  желательно перелогинится - часть настроек  кешируется  для  кускорения работы

**Comment by kirilovsasha** [comment]
> там написано - после изменения настроек желательно перелогинится - часть настроек кешируется для кускорения работы

спасибо!
